#!/usr/bin/env node
"use strict";
const fs=require("fs"),path=require("path"),os=require("os"),http=require("http"),readline=require("readline"),{randomUUID}=require("crypto");
const ROOT=path.resolve(__dirname,"..");
const EXT=path.join(ROOT,"extension");
const SCRIPT=name=>fs.readFileSync(path.join(EXT,name),"utf8");
const BUNDLED_NODE_MODULES=process.env.CODEX_NODE_MODULES||path.join(os.homedir(),".cache","codex-runtimes","codex-primary-runtime","dependencies","node","node_modules");
function playwright(){try{return require("playwright-core")}catch(_){try{return require("playwright")}catch(_){return require(path.join(BUNDLED_NODE_MODULES,"playwright"))}}}
function mediaIdentity(raw){try{const u=new URL(raw),m=u.pathname.match(/^\/(?:[A-Za-z0-9._]+\/)?(p|reels?)\/([A-Za-z0-9_-]+)(?:\/|$)/);if(!m||!/(^|\.)instagram\.com$/i.test(u.hostname))return null;const media_type=m[1]==="p"?"p":"reel";return{shortcode:m[2],media_type,url:`https://www.instagram.com/${media_type}/${m[2]}/`}}catch{return null}}
function alternateMediaUrl(raw){const x=mediaIdentity(raw);if(!x)throw Error("invalid_instagram_media_url");return`https://www.instagram.com/${x.media_type==="p"?"reel":"p"}/${x.shortcode}/`}
function validateSnapshot(requestedUrl,s={}){const wanted=mediaIdentity(requestedUrl),final=mediaIdentity(s.final_url),location=mediaIdentity(s.location_url),rendered=location||final;const supporting=[s.canonical_url,s.og_url,...(s.comment_urls||[])].map(mediaIdentity).filter(Boolean);const shortcodeMismatch=!wanted||!rendered||rendered.shortcode!==wanted.shortcode||supporting.some(x=>x.shortcode!==wanted.shortcode);const routeMismatch=!wanted||!final||!location||final.media_type!==wanted.media_type||location.media_type!==wanted.media_type;return{ok:!!s.page_ready&&!s.visible_error_state&&!shortcodeMismatch&&!routeMismatch,shortcode_mismatch:shortcodeMismatch,route_mismatch:routeMismatch,actual_shortcode:rendered?.shortcode||null,rendered_media_type:rendered?.media_type||null}}
async function connectWithRetry(connector,url,attempts=2){let last;for(let i=0;i<attempts;i++){try{return await connector(url)}catch(e){last=e;if(i+1<attempts)await new Promise(r=>setTimeout(r,300))}}throw last}
function probeCdp(cdpUrl,timeoutMs=2000){return new Promise(resolve=>{let target;try{target=new URL("/json/version",cdpUrl)}catch(e){return resolve({status:"cdp_not_listening",stop_reason:`invalid_cdp_url:${e.message}`})}const req=http.get(target,{timeout:timeoutMs},res=>{let body="";res.setEncoding("utf8");res.on("data",x=>body+=x);res.on("end",()=>{try{const j=JSON.parse(body);resolve(res.statusCode===200&&j.webSocketDebuggerUrl?{status:"ready",browser:j.Browser||null}:{status:"cdp_not_listening",stop_reason:"cdp_version_unavailable"})}catch{resolve({status:"cdp_not_listening",stop_reason:"cdp_version_invalid_json"})}})});req.on("timeout",()=>req.destroy(Error("timeout")));req.on("error",e=>resolve({status:"cdp_not_listening",stop_reason:`cdp_connection_failed:${e.code||e.message}`}))})}
function visibleError(text,url){const v=String(text||"").toLowerCase();if(/http error 429|too many requests|try again later|操作过于频繁/.test(v))return"rate_limited";if(/sorry, this page isn.?t available|page not available|页面不可用/.test(v))return"unavailable";if(/log in to instagram|登录 instagram/.test(v)||/\/accounts\/login/.test(url||""))return"login_required";return null}
function navigationDelay(lastStarted,now,minIntervalMs=15000){return Math.max(0,Number(minIntervalMs)-(Number(now)-Number(lastStarted)))}
function randomDelayMs(min,max,rng=Math.random){const low=Math.min(Number(min),Number(max)),high=Math.max(Number(min),Number(max));return Math.min(high,Math.floor(low+rng()*(high-low+1)))}
class CdpCollector{
  constructor(cdpUrl,{navigationDelayMinMs=20000,navigationDelayMaxMs=35000,clock=()=>Date.now(),sleep=ms=>new Promise(r=>setTimeout(r,ms)),rng=Math.random}={}){this.cdpUrl=cdpUrl;this.browser=null;this.context=null;this.page=null;this.navigationCount=0;this.routesInstalled=false;this.navigationDelayMinMs=Math.max(20000,Number(navigationDelayMinMs)||20000);this.navigationDelayMaxMs=Math.max(this.navigationDelayMinMs,Number(navigationDelayMaxMs)||35000);this.lastInstagramNavigationAt=0;this.clock=clock;this.sleep=sleep;this.rng=rng}
  async connect(){if(this.browser?.isConnected()&&this.context)return;this.browser=await connectWithRetry(url=>playwright().chromium.connectOverCDP(url),this.cdpUrl,2);this.context=this.browser.contexts()[0];if(!this.context)throw Error("cdp_context_missing");if(!this.routesInstalled){await this.context.route(/https:\/\/(static\.cdninstagram\.com|static\.xx\.fbcdn\.net)\//,async route=>{try{const response=await route.fetch(),headers={...response.headers(),"access-control-allow-origin":"*","cross-origin-resource-policy":"cross-origin"};await route.fulfill({response,headers})}catch(_){await route.continue()}});this.routesInstalled=true}this.page=this.context.pages().find(p=>/instagram\.com|google\.com|amazon\.com/i.test(p.url()))||this.context.pages()[0]||await this.context.newPage()}
  async ensurePage(){await this.connect();if(!this.page||this.page.isClosed())this.page=this.context.pages()[0]||await this.context.newPage();return this.page}
  async snapshot(){const page=await this.ensurePage(),final_url=page.url();try{return await page.evaluate(()=>{const text=String(document.body?.innerText||"").slice(0,7000),low=text.toLowerCase();const error=/http error 429|too many requests|try again later|操作过于频繁/.test(low)?"rate_limited":/sorry, this page isn.?t available|page not available|页面不可用/.test(low)?"unavailable":/log in to instagram|登录 instagram/.test(low)?"login_required":null;return{location_url:location.href,location_pathname:location.pathname,canonical_url:document.querySelector('link[rel="canonical"]')?.href||null,og_url:document.querySelector('meta[property="og:url"]')?.content||null,comment_urls:[...document.querySelectorAll('a[href*="/c/"],a[href*="comment_id"]')].map(a=>a.href).slice(0,300),document_ready_state:document.readyState,page_ready:!!document.querySelector("main,article,[role=dialog]"),visible_error_state:error,body_length:text.trim().length}})}catch(e){return{location_url:final_url,location_pathname:null,canonical_url:null,og_url:null,comment_urls:[],page_ready:false,visible_error_state:"browser_error_page",injection_error:String(e.message||e)}}finally{}}
  async waitForInstagramNavigation(url){if(!/(^|\.)instagram\.com$/i.test(new URL(url).hostname))return;const interval=randomDelayMs(this.navigationDelayMinMs,this.navigationDelayMaxMs,this.rng),wait=navigationDelay(this.lastInstagramNavigationAt,this.clock(),interval);if(wait)await this.sleep(wait);this.lastInstagramNavigationAt=this.clock();return{interval_ms:interval,slept_ms:wait}}
  async assertNotRateLimited(){const page=await this.ensurePage(),text=await page.evaluate(()=>String(document.body?.innerText||"").slice(0,7000)).catch(()=>"");if(visibleError(text,page.url())==="rate_limited")throw Error("rate_limited")}
  async goto(url){const page=await this.ensurePage();await this.waitForInstagramNavigation(url);let response=null;try{response=await page.goto(url,{waitUntil:"domcontentloaded",timeout:60000})}catch(_){}if(response?.status()===429)throw Error("rate_limited");await page.waitForTimeout(1500);await this.assertNotRateLimited();return page}
  async reload(){const page=await this.ensurePage();await this.waitForInstagramNavigation(page.url());let response=null;try{response=await page.reload({waitUntil:"domcontentloaded",timeout:60000})}catch(_){}if(response?.status()===429)throw Error("rate_limited");await page.waitForTimeout(1200);await this.assertNotRateLimited();return page}
  async clickDiscovered(sourceUrl,targetUrl){if(!sourceUrl)return false;let host="";try{host=new URL(sourceUrl).hostname}catch{return false}if(!["www.instagram.com","instagram.com","www.google.com","www.bing.com"].includes(host))return false;await this.goto(sourceUrl);const target=mediaIdentity(targetUrl),current=mediaIdentity(this.page.url());if(!target)return false;if(current?.shortcode===target.shortcode)return true;await this.waitForInstagramNavigation(targetUrl);return this.page.evaluate(({code})=>{const parse=v=>{try{return new URL(v).pathname.match(/^\/(?:[A-Za-z0-9._]+\/)?(?:p|reels?)\/([A-Za-z0-9_-]+)(?:\/|$)/)?.[1]||null}catch{return null}};const a=[...document.querySelectorAll("a[href]")].find(x=>parse(x.href)===code);if(!a)return false;a.removeAttribute("target");a.target="_self";a.click();return true},{code:target.shortcode}).catch(()=>false)}
  async navigateMedia(payload){const page=await this.ensurePage(),discovery_url=payload.discovery_url||payload.url,previous_url=page.url(),navigation_id=randomUUID(),navigation_started_at=new Date().toISOString(),attempts=[];const routes=[payload.url,alternateMediaUrl(payload.url)];for(let i=0;i<routes.length;i++){const requested=routes[i],before=await this.snapshot(),beforeCheck=validateSnapshot(requested,{...before,final_url:page.url()});if(beforeCheck.ok){attempts.push({method:"current_page",requested_url:requested,...before,...beforeCheck});return{navigation_id,tab_id:null,previous_url,discovery_url,requested_url:requested,requested_media_type:mediaIdentity(requested).media_type,rendered_url:before.location_url,rendered_media_type:beforeCheck.rendered_media_type,working_media_url:requested,navigation_started_at,navigation_completed_at:new Date().toISOString(),route_fallback_attempt_count:i,route_fallback_success_count:i?1:0,attempts}}
      let clicked=false;if(i===0)clicked=await this.clickDiscovered(payload.navigation_source_url,requested);if(!clicked)await this.goto(requested);else await page.waitForTimeout(2000);let snap=await this.snapshot(),check=validateSnapshot(requested,{...snap,final_url:page.url()});attempts.push({method:clicked?"discovery_anchor":"page_goto",requested_url:requested,...snap,...check,completed_at:new Date().toISOString()});if(check.ok)return{navigation_id,tab_id:null,previous_url,discovery_url,requested_url:requested,requested_media_type:mediaIdentity(requested).media_type,rendered_url:snap.location_url,rendered_media_type:check.rendered_media_type,working_media_url:requested,navigation_started_at,navigation_completed_at:new Date().toISOString(),route_fallback_attempt_count:i,route_fallback_success_count:i?1:0,attempts};if(snap.visible_error_state==="rate_limited")throw Object.assign(Error("rate_limited"),{navigation:{navigation_id,previous_url,discovery_url,requested_url:requested,attempts}});if(check.shortcode_mismatch)break;if(check.route_mismatch&&!snap.visible_error_state)continue;await this.reload();snap=await this.snapshot();check=validateSnapshot(requested,{...snap,final_url:page.url()});attempts.push({method:"reload",requested_url:requested,...snap,...check,completed_at:new Date().toISOString()});if(check.ok)return{navigation_id,tab_id:null,previous_url,discovery_url,requested_url:requested,requested_media_type:mediaIdentity(requested).media_type,rendered_url:snap.location_url,rendered_media_type:check.rendered_media_type,working_media_url:requested,navigation_started_at,navigation_completed_at:new Date().toISOString(),route_fallback_attempt_count:i,route_fallback_success_count:i?1:0,attempts};if(snap.visible_error_state==="rate_limited")throw Object.assign(Error("rate_limited"),{navigation:{navigation_id,previous_url,discovery_url,requested_url:requested,attempts}});if(check.shortcode_mismatch)break}
    const last=attempts[attempts.length-1]||{},reason=last.visible_error_state||(last.shortcode_mismatch?"MEDIA_ID_MISMATCH_NAVIGATION":"instagram_media_route_error_page"),e=Error(reason);e.navigation={navigation_id,previous_url,discovery_url,requested_url:last.requested_url||payload.url,requested_media_type:mediaIdentity(last.requested_url||payload.url)?.media_type||null,rendered_url:last.location_url||this.page.url(),rendered_media_type:last.rendered_media_type||null,working_media_url:null,navigation_started_at,navigation_completed_at:new Date().toISOString(),route_fallback_attempt_count:1,route_fallback_success_count:0,attempts};throw e}
  async evalScript(name){return this.page.evaluate(SCRIPT(name))}
  async loginState(){return this.page.evaluate(()=>{const text=String(document.body?.innerText||"");return{url:location.href,login_visible:!!document.querySelector('input[name="username"],input[name="email"],input[type="password"],a[href*="/accounts/login"]')||/log in|登录/i.test(text),instagram_ui:!!document.querySelector('a[href="/direct/inbox/"],a[href="/explore/"],nav')}})}
  async prepareActiveReel(expectedShortcode){
    let state=await this.page.evaluate(()=>globalThis.InstagramVocCapture.commentState()),clicked=false;
    if(!state.ready){
      clicked=await this.page.evaluate(()=>{const core=globalThis.InstagramVocCore,seen=new Set(),rows=[];for(const raw of document.querySelectorAll('button,[role="button"],[aria-label],svg[aria-label]')){const labels=[raw.textContent,raw.getAttribute?.('aria-label'),raw.getAttribute?.('title'),raw.querySelector?.('svg[aria-label]')?.getAttribute('aria-label')];if(!labels.some(core.isCommentTriggerLabel))continue;const el=raw.closest?.('button,[role="button"],a[href]')||raw;if(seen.has(el))continue;seen.add(el);const r=el.getBoundingClientRect();if(r.width<=0||r.height<=0||r.bottom<=0||r.top>=innerHeight)continue;rows.push({el,distance:Math.abs((r.top+r.bottom)/2-innerHeight/2)})}rows.sort((a,b)=>a.distance-b.distance);if(!rows[0])return false;rows[0].el.scrollIntoView({block:'center',behavior:'auto'});rows[0].el.click();return true});
      const deadline=Date.now()+12000;while(clicked&&!state.ready&&Date.now()<deadline){await this.page.waitForTimeout(500);state=await this.page.evaluate(()=>globalThis.InstagramVocCapture.commentState())}
    }
    const actual=mediaIdentity(this.page.url());if(actual?.shortcode!==expectedShortcode)throw Error('MEDIA_ID_MISMATCH_NAVIGATION');
    const result={ready:!!state.ready,empty:!!state.empty,media_type:'reel',comment_icon_clicks:clicked?1:0,node_count:state.node_count||0,pending_controls:state.pending_controls||0,frontier:state.frontier||{},prepared_at:new Date().toISOString()};await this.page.evaluate(x=>globalThis.__IG_VOC_PREPARE_RESULT__=x,result);return result
  }
  async run(kind,payload){await this.ensurePage();if(kind==="preflight"){await this.goto("https://www.instagram.com/");const state=await this.loginState();return{status:state.login_visible||!state.instagram_ui?"waiting_for_manual_login":"ready",extension_id:null,...state}}await this.assertNotRateLimited();if(kind==="inspect_product"){await this.goto(payload.url);return this.evalScript("amazon_capture.js")}if(kind==="discover_query"){await this.goto(payload.url);await this.page.evaluate(x=>globalThis.__IG_DISCOVERY_JOB__=x,payload);await this.evalScript("bridge_core.js");return this.evalScript("discovery_capture.js")}if(kind==="inspect_media"){try{const navigation=await this.navigateMedia(payload);await this.evalScript("capture_core.js");const metadata=await this.evalScript("media_metadata.js");return{...metadata,navigation,requested_url:navigation.requested_url,requested_media_type:navigation.requested_media_type,rendered_url:navigation.rendered_url,rendered_media_type:navigation.rendered_media_type,working_media_url:navigation.working_media_url,route_fallback_attempt_count:navigation.route_fallback_attempt_count,route_fallback_success_count:navigation.route_fallback_success_count}}catch(e){if(!e.navigation)throw e;return{identity_verified:false,stop_reason:e.message,navigation:e.navigation,requested_url:e.navigation.requested_url,requested_media_type:e.navigation.requested_media_type,rendered_url:e.navigation.rendered_url,rendered_media_type:e.navigation.rendered_media_type,working_media_url:null,route_fallback_attempt_count:e.navigation.route_fallback_attempt_count,route_fallback_success_count:0}}}if(kind==="collect_media"){const navigation=await this.navigateMedia(payload);const options={...(payload.options||{}),expected_media_type:navigation.requested_media_type,expected_media_url:navigation.working_media_url};await this.page.evaluate(({o,id})=>{globalThis.__IG_VOC_OPTIONS__=o;globalThis.__IG_VOC_JOB_ID__=id;globalThis.__IG_VOC_STOP_REQUESTED__=false},{o:options,id:payload.navigation_id||navigation.navigation_id});await this.evalScript("capture_core.js");await this.evalScript("capture.js");if(navigation.rendered_media_type==='reel')await this.prepareActiveReel(payload.shortcode);else await this.evalScript("media_prepare.js");const capture=await this.evalScript("continuous_capture.js");capture.navigation=navigation;capture.media={...(capture.media||{}),working_media_url:navigation.working_media_url,rendered_media_type:navigation.rendered_media_type,rendered_url:navigation.rendered_url};return capture}throw Error(`unsupported_job:${kind}`)}
  async close(){this.browser=null;this.context=null;this.page=null}
}
async function worker(cdpUrl,navigationDelayMinMs=20000,navigationDelayMaxMs=35000){const probe=await probeCdp(cdpUrl);if(probe.status!=="ready"){console.log(JSON.stringify({type:"ready",ok:false,...probe}));return 2}const c=new CdpCollector(cdpUrl,{navigationDelayMinMs,navigationDelayMaxMs});try{await c.connect();console.log(JSON.stringify({type:"ready",ok:true,transport:"cdp",cdp_url:cdpUrl,extension_id:null}));const rl=readline.createInterface({input:process.stdin,crlfDelay:Infinity});for await(const line of rl){if(!line.trim())continue;let request;try{request=JSON.parse(line);const result=await c.run(request.kind,request.payload||{});console.log(JSON.stringify({id:request.id,ok:true,result}))}catch(e){console.log(JSON.stringify({id:request?.id||null,ok:false,error:String(e.message||e),navigation:e.navigation||null}))}}return 0}finally{await c.close()}}
function parseArgs(argv){const o={command:"worker",cdpUrl:"http://127.0.0.1:9333",navigationDelayMinMs:20000,navigationDelayMaxMs:35000};let i=0;if(argv[0]&&!argv[0].startsWith("--"))o.command=argv[i++];for(;i<argv.length;i++){const k=argv[i],v=argv[++i];if(k==="--cdp-url")o.cdpUrl=v;else if(k==="--navigation-delay-min-ms")o.navigationDelayMinMs=Math.max(20000,Number(v)||20000);else if(k==="--navigation-delay-max-ms")o.navigationDelayMaxMs=Math.max(20000,Number(v)||35000);else if(k==="--help"||k==="-h")o.help=true;else throw Error(`unknown_argument:${k}`)}o.navigationDelayMaxMs=Math.max(o.navigationDelayMinMs,o.navigationDelayMaxMs);return o}
async function main(){const o=parseArgs(process.argv.slice(2));if(o.help){console.log("Usage: node scripts/instagram_playwright_collector.cjs worker --cdp-url http://127.0.0.1:9333 --navigation-delay-min-ms 20000 --navigation-delay-max-ms 35000");return}const code=await worker(o.cdpUrl,o.navigationDelayMinMs,o.navigationDelayMaxMs);process.exit(code)}
module.exports={mediaIdentity,alternateMediaUrl,validateSnapshot,connectWithRetry,probeCdp,CdpCollector,parseArgs,navigationDelay,randomDelayMs};
if(require.main===module)main().catch(e=>{console.error(e.stack||e);process.exitCode=1});
